services:
  - type: web
    name: el-rasho
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: el-rasho-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
